### ISSUE TITLE
database

### ISSUE THREAD

**Issue by Ronin-0822** [aaron-san/vocab-builder#3]
For the login/signup stuff and authentication for registered users, we need a database.

How do you handle data storage in your projects? Are you familiar with databases, for example MySQL? 

I'm using databases in all my projects, so if you want me to set up a database with tables that handle the users, and every thing that's needed for a secure login/authentication system I can go ahead and do that. After I have it set up on my local machine, I can upload some files you can use to easily recreate the database on your local environment (such files are called migration files, they make sure that databases are consistent across environments).

**Comment by aaron-san** [comment]
Yes, I have used MySQL before. I have used MongoDB more. Either is fine. Please send me the migration files. I'll figure out how to recreate it. I have been trying out Docker as well. It's possible to create a Docker image for a MySQL or Mongo database that we could both use safely without worrying about local machine configuration issues. As long as you have Docker Desktop installed, we would use the same Docker file that runs the database. It takes a bit of configuration and I've never done it, but maybe I could get it running. If it's easy for you, please do set up a database and send me the migration files. I don't mind setting up the Docker image if you're comfortable with that too.

**Comment by Ronin-0822** [comment]
Sure, I've never used Docker, but it's also on the list of things I've wanted to learn for a while. I'll go ahead and create the database and the migration files (hopefully within the next few days).

I've never used MongoDB. Is there a big difference to MySQL? I've only worked with MySQL so far.

**Comment by Ronin-0822** [comment]
I've just uploaded the database "migration" file. Actually, it's just an sql dump file containing the database structure. You should be able to import the file using phpMyAdmin, or just by running the sql commands.
In addition to the "users" table I've included some other tables that will be necessary for the "forgot password" and "remember me" functionality.
Let me know if you have any questions or suggestions.

**Comment by aaron-san** [comment]
Thank you!

In UserModel.php I tried to connect to the .sql file, but PDO is not recognized on my machine. 
Do you know how to access the database on the server? For now, we are using hardcoded data, which is fine. I was curious if it's easy to connect to the database. I tried the following (commented out) without success:

<?php

namespace App\Models;

// $env = parse_ini_file('../../.env');
// $mysql_username = $env["MYSQL_USERNAME"];
// $mysql_password = $env["MYSQL_PASSWORD"];

// $dsn = "mysql:host=localhost;dbname=mydatabase;charset=utf8mb4";
// $db = new PDO($dsn, $user, $password);
// $sql = file_get_contents('../../vocab_builder.sql');
// $qr = $db->exec($sql);

class UserModel

**Comment by aaron-san** [comment]
For some reason, it got cut out. Here it is again.

namespace App\Models;

$env = parse_ini_file('../../.env');
$mysql_username = $env["MYSQL_USERNAME"];
$mysql_password = $env["MYSQL_PASSWORD"];

$dsn = "mysql:host=localhost;dbname=mydatabase;charset=utf8mb4";
$db = new PDO($dsn, $user, $password);
$sql = file_get_contents('../../vocab_builder.sql');
$qr = $db->exec($sql);

class UserModel
{
