### ISSUE TITLE
Business Idea

### ISSUE THREAD

**Issue by Ronin-0822** [aaron-san/vocab-builder#4]
Ok, here's my idea:

I want to make an English vocab app, similar to this [Japanese App](https://japaneseapp.com/) that I had been using when I was still trying to learn kanji. Maybe with less features, but I really like its flashcard study features. It has organized the kanji into various different groups (school grade level, JLPT, categories). It also allows you to make your own deck of flashcards, add notes/tags to individual cards. When you study you can swipe the card right (remembered) or left (not remembered) and it color marks the card either yellow (started), blue (memorized) or green (learned). According to the color, the cards appear more or less frequently when you study or review them.

I would like to continue the MVC repo for learning purpose, but I think to build the actual app using a framework (CodeIgniter or Laravel) would be a lot easier and speed up the process significantly. I am already renting a server for my other sites, so we could deploy it there for production (only need a good domain for it).

For the pricing I was thinking to go annual subscription and/or possible one-time-purchase. I'm paying for the server anyways, so if we don't get any sales that's not a big deal. 

I don't have much time to write, I just wanted to get it out for now. 
Apparently there is a lot more that needs to be discussed, but let me know your thoughts.

**Comment by aaron-san** [comment]
Interesting idea. I like it. Are you familiar with CodeIgniter or Laravel? Are you thinking about taking the lead in frontend then? I would have to learn these, but now that I know what direction to go I can go faster using React. If you feel like doing it in a different language that's fine too. I'm not sure what's best. By the way, what's your server provider again?

**Comment by Ronin-0822** [comment]
Great. Glad you like it. 
I'm familiar with CodeIgniter, but I think I could probably pick up Laravel on the go. I mean Laravel has kind of been the big player of the PHP frameworks in recent years, and it's geared towards more complicated applications. Also setting up the environment can be more complicated compared to CodeIgniter. It also comes with a lot of functionality that we most likely wouldn't be using.
CodeIgniter is a lightweight and powerful framework as well. It's compact and more resource-efficient than Laravel.
I'm sure CI has everything we need, and since I'm already familiar with it development would definitely be faster.
Let's go with CodeIgniter backend (my lead), and I'll leave the choice of frontend framework to you. Feel free to use any CSS library you want.
I'll go ahead and create a new repo with a folder called "backend" for CodeIgniter. 
```
/vocab-app
    /frontend
        /React stuff
   /backend
        /CodeIgniter
```
Let me know if that sounds good.

Oh, the provider I'm using is [value-domain](https://www.value-domain.com/). The server package I'm renting is the [Coreserver Core-Y](https://www.coreserver.jp/).

**Comment by Ronin-0822** [comment]
If you have any ideas for a domain name, let me know.

For example "vocabsensei.com" would still be available for 780yen. 😉

**Comment by aaron-san** [comment]
Wonderful! Yes, makes sense now. I thought CodeIgniter was a front-end framework at first, but it's a backend framework. So, you were using vanilla PHP so far? What exactly will you build with CodeIgniter? What I saw in the current code base is a rendered server-side html page with a list of users. So the server rendered the front-side and we don't need React in that case. However, if you build an API then React could access it and render what we tell it using React code. Does that make sense? Ultimately, will this be a server-side rendered site or a client-side rendered site (i.e., using React)?

**Comment by aaron-san** [comment]
The directory structure you proposed sounds good and "vocabsensei.com" is a great choice, I think!

**Comment by Ronin-0822** [comment]
> The directory structure you proposed sounds good and "vocabsensei.com" is a great choice, I think!

Thanks. Should I go ahead and get the domain then?

**Comment by Ronin-0822** [comment]
Oh, I thought "frontend" was just a miswording on your side...hahaha. 
Yes, CodeIgniter is a backend framework. In the MVC repo I'm only using vanilla PHP. You had mentioned that you were interested in learning PHP as well, so I thought it to be better not to use a framework. I am kind of rebuilding a way simpler imitation of CodeIgniter, though. 

CodeIgniter will be the Model and Controller layer in the new app. It will handle user authentication, database communication, any kind of data validation. So the controller receives a client request, e.x. `/user/dashboard` , it then talks to the model(s) in order to get all the necessary data from the database. Finally, the controller returns a view file, which in the recent codebase (you're right) is an html file on the server, and pass it the data as an array. 
I have never used a frontend framework, so I don't know how, but the View layer would be handled by React, right?
Maybe the controller would only return the data array without the view file?
I like the idea of the app being a client-side rendered site, that seems to be the trend with a lot of apps these days, and you being familiar with React can only make things easier...

I'll go ahead and set up the backend part in the repo and create routes for a `home` and `about` page. Once that's done, you can add the React stuff to it and we can figure out how to connect the front to the backend. What do you think?
I'll invite you to the repo once I've finished the initial backend setup.

**Comment by aaron-san** [comment]
I see. CodeIgniter is much like Express in Node. Yes, React will be the View layer. It will contain all the HTML, CSS and JavaScript needed for the user frontend experience. React will fetch the API end points (e.g., `/user/dashboard`) and use the API response when rendering the webpages. Yes, the controller would return the JSON data in this case. Sounds good! I'll add the React stuff.

**Comment by aaron-san** [comment]
> > The directory structure you proposed sounds good and "vocabsensei.com" is a great choice, I think!
> 
> Thanks. Should I go ahead and get the domain then?

I'm not sure, actually. It's pretty cheap, so we can go ahead and do that. I don't know when we'll decide to go live, but you can get it now if you want. I'll buy you a beer or something to help cover the cost. haha

**Comment by Ronin-0822** [comment]
Ok, `www.vocabsensei.com` is now ours.
> I'll buy you a beer or something to help cover the cost.

Beer sounds good. haha

I've sent you an invite to the vocabsensei repo. I've also added some comments to the README file regarding necessary steps BEFORE installing React. Please make sure to read those first. Let me know if you have any questions.
I'll wait with any other work until we have the React stuff working as well.
